package entites.payments_package;


public enum PaymentStatus {
    PENDING, COMPLETED, FAILED, REFUNDED, 
    CANCELLED, PROCESSING, ON_HOLD, DISPUTED, 
    PARTIALLY_REFUNDED, AUTHORIZED, DECLINED, 
    EXPIRED, SETTLED, REVERSED, AWAITING_CONFIRMATION, 
    SUCCESSFUL, UNSUCCESSFUL, IN_PROGRESS, MANUAL_REVIEW
}