package entites.tables_package;


public enum SeatType {
    BAR, BOOTH, WHEELCHAIR_ACCESSIBLE, HIGH_CHAIR, 
    REGULAR, KID, ACCESSIBLE, OTHER, COUNTER, 
    PATIO, LOFT, PRIVATE, FAMILY, LOUNGE, 
    STANDING, VIP, BALCONY, FRONT_ROW, 
    BACK_ROW, SIDE, CENTER, OUTDOOR, 
    INDOOR, RESERVED, GROUP, SINGLE, 
    DOUBLE, TRIPLE
}