package entites.tables_package;

public enum TableStatus {
    FREE, RESERVED, OCCUPIED, CANCELED, 
    WAITLISTED, IN_SERVICE, OUT_OF_SERVICE, 
    PENDING, UNAVAILABLE, READY_FOR_CLEANING, 
    BEING_CLEANED, BOOKED, CHECKED_OUT, 
    TEMPORARILY_CLOSED, RESERVED_FOR_EVENT, 
    PARTIALLY_OCCUPIED
}
