package entites.reservations_package;

public enum ReservationStatus {
    PENDING, CONFIRMED, CANCELED, ABANDONED, 
    COMPLETED, NO_SHOW, MODIFIED, EXPIRED, 
    WAITLISTED, REJECTED, IN_PROGRESS, VERIFIED, 
    PARTIALLY_CONFIRMED, AWAITING_PAYMENT, 
    CANCELLED_BY_USER, CANCELLED_BY_SYSTEM, RESCHEDULED
}