package entites.accounts_package;

public enum AccountStatus {
    ACTIVE, CLOSED, CANCELED, BLACKLISTED, SUSPENDED, 
    PENDING, FROZEN, INACTIVE, ARCHIVED, DELETED, 
    VERIFIED, UNVERIFIED, LOCKED, REINSTATED, 
    EXPIRED, TERMINATED, UNDER_REVIEW, DORMANT, SUSPICIOUS
}
